import type { Metadata } from "next";
import "./globals.css";
import Provider from "@/provider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="w-full min-h-screen bg-linear-to-b from-green-400 to-white"
      ><Provider>{children}</Provider>
        {children}
      </body>
    </html>
  );
}
